### ISSUE TITLE
Lazy translated texts can not be flashed in Flask 0.10

### ISSUE THREAD

**Issue by zgoda** [python-babel/flask-babel#31]
Because they are not JSON-serializable. This is new limitation in Flask 0.10.

**Comment by j3hyde** [comment]
I've been running into this issue as of today and find that the problem is spread out.  Flask instantiates the `JSONEncoder`, Flask-Babel calls `speakerlater.make_lazy_string()`, and that returns a `_LazyString`.

The crux of the issue is that Flask-Babel doesn't have access to or influence over the `JSONEncoder`.  Although Flask's `JSONEncoder` will call an object's `__html__()` method if it exists to encode the object, Flask-Babel can't modify `_LazyString` to add such a method because `_LazyString.__slots__` is defined.

I see a few long-term solutions:
 1. Proxy the `_LazyString` returned by `speaklater.make_lazy_string` and provide an `__html__` implementation.  It seems like performance could suffer in high usage but I haven't measured.  However, this enables ongoing use of `speaklater.make_lazy_string`.

 See this is in this pull request:  https://github.com/python-babel/flask-babel/pull/81

 2. ~~Sneakily~~Dynamically sublcass `_LazyString` to add a slot and provide `__html__`.  Then return this instead.  This seems brittle since speakerlater's API is really the `make_lazy_string` factory but this neatly avoids any performance issues and seems pretty straight-forward to understand/implement.

 See this pull request:  https://github.com/python-babel/flask-babel/pull/82

 3. Lobby the speaklater project to add an __html__ method as they did `__getstate__` and `__setstate__` methods for pickle except that __html__ is special to Flask and not general to jsonify.

Lastly, as a short-term, work-around solution for anyone else hitting this problem, you can change your app from doing this:

    login_manager.login_message = lazy_gettext('Please log in to access this page.')

To using an incomplete proxy (ideally it would would add `__getattr__` and friends):

    class lazy_login_message(object):
        def __init__(self, lazy_string):
            self.ls = lazy_gettext(lazy_string)

        def __html__(self):
            return unicode(self.ls)

    login_manager.login_message = lazy_login_message('Please log in to access this page.')

This assumes that the only consumer of the string is going to jsonify it with Flask's JSONEncoder.
